### ISSUE TITLE
Subcommand: Batch

### ISSUE THREAD

**Issue by tboerger** [crowbar/crowbar-client#5]
We need more subcommands, this issue handles the subcommands for batch:

* [x] Build
* [x] Export

**Comment by aspiers** [comment]
export is supposed to dump all barclamps by default but it doesn't dump anything:

```
root@crowbar:~ # rpm -qf `which crowbarctl`
ruby2.1-rubygem-crowbar-client-2.2.1-1.1.x86_64
root@crowbar:~ # crowbarctl batch export
root@crowbar:~ # 
```

**Comment by tboerger** [comment]
> export is supposed to dump all barclamps by default but it doesn't dump anything:

Of course it doesn't dump anything, as you can see on this issue, our trello card and within the code it's currently noop code :D

**Comment by aspiers** [comment]
Hmm, I thought you said in the workshop it was done. Guess I imagined that :)

**Comment by tboerger** [comment]
> Hmm, I thought you said in the workshop it was done. Guess I imagined that :)

No, I said batch and reset are missing :)
